# Generated by Django 3.0.5 on 2020-04-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
