# Generated by Django 3.0.5 on 2020-04-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20200408_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
