# Generated by Django 3.0.5 on 2020-04-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_destination_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='subcategory',
            field=models.TextField(blank=True, null=True),
        ),
    ]
