# Generated by Django 3.0.5 on 2020-04-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_destination_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
