# Generated by Django 3.0.5 on 2020-04-18 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_destination_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='slug',
        ),
    ]
