# Generated by Django 3.0.5 on 2020-04-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='Questions',
        ),
    ]
