# Generated by Django 3.0.5 on 2020-04-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0016_auto_20200425_0737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndustryType',
        ),
    ]
