# Generated by Django 3.0.5 on 2020-04-25 11:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0021_auto_20200425_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], max_length=49, null=True),
        ),
    ]
