# Generated by Django 3.0.5 on 2020-04-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0022_auto_20200425_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
